
var GAME_LEVELS = [
  ["                                                                                       ",
   "                                                                                       ",
   "                                                                                       ",
   "                                                                                       ",
   "                                                                           xx!xx       ",
   "                                                   o   ppp   o             xx!xx       ",
   "                                                                 xx!xx      xvx        ",
   "                                      o y o y o   xxx       xxx  x!!!x                 ",
   "                                                                 x!!!x                 ",
   "                                o     xxxxxxxxx                  xx!xx                y",
   "                                                                  xvx                  ",
   "                               xxx                                                   xx",
   "  x                      ooo                                                          x",
   "  x                    xxxxxxx                                                        x",
   "  x    o               x     x        o         o                                     x",
   "  x           xxxx     x     x                                                        x",
   "  x    @      x  x     x     x                                    xxxxx             o x",
   "  xxxxxxxxxxxxx  xxxxxxx     xx   xxxxxxxx  xxxxxxxxxx y y xxxxxxx     xxxxxxxxxxxxxxxx",
   "                              x | x      xxxx        x  |  x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     o               o                                     v v                           ",
   "       v                   v                  v                 v        p        v                v                  v                                                          oooo                                              ",
   "                                                      ooo                                                    ooo                                                                                                             ooo   ",
   "                                                                                                                                                        o                 o                                                        ",
   "xxxxxxx xxxxxxxxxxxxxxxxxxx xxxxxx       xxxxx xxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxx xxxxxx      xxxx xxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxooooo                                                                                          ",
   "                                                                        ppp                                  ppp                         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxx",
   " @            oooooooo              xxx      ooo                      oooooooo            xxx             ooo   ooo                     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                   xxxxx                                                 xxxxx                                         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   ],
  ["                                                                                                                                          ",
   "                 vvv                                                                                                                      ",
   "                                                                                                                                          ",
   "                                                                                                                                          ",
   "                                                                                                                                          ",
   "                                                                                                                                          ",
   "                                                                                                                                          ",
   "                                        o                                                                                                 ",
   "                                        o                                                                                                 ",
   "                                        o                                                                                                 ",
   "                                        x                                                                                                 ",
   "                                       xpx                                                                                                ",
   "                                       x x                                                                                                ",
   "                                       x x                                                                                                ",
   "                                      xx xx                                                                                               ",
   "                                      x   x                                                                                               ",
   "                                      x   x                                                                                               ",
   "                                      x   x                                                                                               ",
   "                                     xx   xx                                                                                              ",
   "                                      x   xxxxxxxx   xxxxxxxxxxxx           ppp                                                           ",
   "                                      x   x           xvvvvvvvvvv          ppppp                                                          ",
   "                                      x   x           x                     ppp                                                           ",
   "                                    xxx   xx          x                                                                                   ",
   "                                      x   xp = = =    x                                                                                   ",
   "                                      x   x           x                                                                                   ",
   "                                      x   x    = = =  x                      xxx                                                          ",
   "                                   xxxx   xx          x                     x!!!x                                                         ",
   "                              o   o   x   x           x                      xvx        xxx                                               ",
   "                                      x   x           x              x                 x!!!x                                              ",
   "                             xxx xxx xxx xxx     o o  x!!!!!!!!!!!!!!x                  xvx                                               ",
   "                             x!!!!!!!!!!!!!x   xxxxxxxx!!!!!!!!!!!!!!x                                                                    ",
   "                         xxp x!!!!!!!!!!!!!x   xxxxxxxxxxxxxxxxxxxxxxx                                                                    ",
   "                             xxxxxx   xxxxxx                                         xxx                                                  ",
   "  x                           x     v     x                                         x!!!x                   x   x xxx  x x    ",
   "  x                           x    x x    x                                          xvx                     x x  x x  x x    ",
   "  x                  xxx      x    x x    xxxxxxp                        xxxxx                                x   x x  x x    ",
   "  x                           x           x                              x   x                                x   xxx  xxx    ",
   "  x                           xx          x                              x p x                                                ",
   "  x                xxx                    x        xxxx      xxxx       xx xxx                                                ",
   "  x                ppp             o o    x                              x                                   x   x  x  xx  x  ",
   "  x               xxxxx       xx          x                             xxx       xooox          o           x x x  x  x x x  ",
   "  x               ppppp       x    xxx    x                            x  x       xxxxx         xxx ooooooox xx xx  x  x  xx  ",
   "  x                           xpxxxxxxxxxpx  x oo x    x oo x    x oo  x  xx                    xxx ooooooox                  ",
   "  x      @          o         x           x!!x    x!|!!x    x!||!x    xx   xx                    p  ooooooox                  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                  ",
   "                                                                                                                                           ",
   "                                                                                                                                           "],

];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
